# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Thanmai Bindi
paginate:       5
baseurl:        ""
url:            "https://tbindi.github.io/tale"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Thanmai Bindi
  url:          http://tbindi.github.io/
  email:        bindithanmai@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/tbindi/tale

# Gems
gems:
  - jekyll-paginate
